import { User, Listing, Review, Conversation, Message } from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user_1',
    name: 'Manuel Kassoma',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    phone: '+244 923 456 789',
    province: 'Luanda',
    city: 'Luanda',
    neighborhood: 'Maianga',
    bio: 'Vendedor particular de artigos de eletrónica e som. Pontual nos encontros na Maianga e Mutamba.',
    joinedYear: 2023,
    isVerified: true,
    rating: 4.9,
    reviewCount: 18,
    lastActive: 'Ativo agora',
    isOnline: true,
  },
  {
    id: 'user_2',
    name: 'Esperança dos Santos',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    phone: '+244 931 112 233',
    province: 'Luanda',
    city: 'Belas',
    neighborhood: 'Kilamba (Quarteirão F)',
    bio: 'Mãe e empreendedora. Vendo roupas, brinquedos das crianças e artigos para o lar que já não usamos.',
    joinedYear: 2024,
    isVerified: true,
    rating: 4.8,
    reviewCount: 12,
    lastActive: 'Visto há 15 min',
    isOnline: false,
  },
  {
    id: 'user_3',
    name: 'Kelson Domingos',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    phone: '+244 944 889 900',
    province: 'Luanda',
    city: 'Talatona',
    neighborhood: 'Morro Bento',
    bio: 'Gamer e entusiasta de tecnologia. Troco e vendo consolas e acessórios no Belas Shopping.',
    joinedYear: 2023,
    isVerified: true,
    rating: 5.0,
    reviewCount: 24,
    lastActive: 'Ativo agora',
    isOnline: true,
  },
  {
    id: 'user_4',
    name: 'Tânia Baptista',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
    phone: '+244 912 345 670',
    province: 'Benguela',
    city: 'Lobito',
    neighborhood: 'Restinga',
    bio: 'Designer e decoradora. Vendo peças de mobiliário e calçado semi-novos no Lobito e Benguela.',
    joinedYear: 2024,
    isVerified: false,
    rating: 4.7,
    reviewCount: 7,
    lastActive: 'Visto há 2 horas',
    isOnline: false,
  },
  {
    id: 'user_current',
    name: 'Kieza Andrade (Você)',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
    phone: '+244 928 765 432',
    province: 'Luanda',
    city: 'Cazenga',
    neighborhood: 'Mabor / Hoji-ya-Henda',
    bio: 'Comprador e vendedor ativo na Zunga. Prefiro entregas no Shoprite do Palanca ou Cazenga.',
    joinedYear: 2024,
    isVerified: true,
    rating: 4.9,
    reviewCount: 9,
    lastActive: 'Ativo agora',
    isOnline: true,
  }
];

// Reference auction end dates relative to today
const inHours = (hours: number) => new Date(Date.now() + hours * 3600 * 1000).toISOString();
const inDays = (days: number) => new Date(Date.now() + days * 24 * 3600 * 1000).toISOString();

export const INITIAL_LISTINGS: Listing[] = [
  {
    id: 'listing_1',
    title: 'iPhone 12 Pro 128GB Grafite - Bateria 87%',
    description: 'Vendo iPhone 12 Pro em ótimo estado de conservação, sem riscos no ecrã. Acompanha caixa original e cabo de carregamento rápido. Aceito testar na hora do encontro. Venda em mãos na Maianga ou Luanda Shopping.',
    category: 'Telemóveis & Tablets',
    condition: 'bom_estado',
    type: 'fixed',
    price: 320000,
    images: [
      'https://images.unsplash.com/photo-1605236453806-6ff36851218e?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=800&auto=format&fit=crop&q=80'
    ],
    sellerId: 'user_1',
    province: 'Luanda',
    city: 'Luanda',
    neighborhood: 'Maianga',
    createdAt: '2026-09-28T14:30:00Z',
    isNegotiable: true,
    isSold: false,
    reactions: { like: 24, fire: 11, deal: 8, negotiate: 15 },
    userReactions: [{ userId: 'user_2', type: 'like' }],
    viewsCount: 342,
  },
  {
    id: 'listing_2',
    title: 'LEILÃO: Gerador Kipor 5.5 kVA Diesel - Partida Elétrica',
    description: 'Gerador silencioso Kipor 5.5 kVA a diesel, revisado recentemente pela oficina autorizada. Ideal para residência quando falha a luz da ENDE. Pega de primeira. Leilão com lance inicial baixo para fechar até amanhã!',
    category: 'Ferramentas & Geradores',
    condition: 'bom_estado',
    type: 'auction',
    price: 450000, // starting price
    currentBid: 580000,
    minIncrement: 20000,
    auctionEndsAt: inHours(14),
    bids: [
      {
        id: 'bid_1',
        listingId: 'listing_2',
        bidderId: 'user_2',
        bidderName: 'Esperança dos Santos',
        bidderLocation: 'Kilamba',
        amount: 480000,
        timestamp: '2026-09-28T18:00:00Z',
      },
      {
        id: 'bid_2',
        listingId: 'listing_2',
        bidderId: 'user_3',
        bidderName: 'Kelson Domingos',
        bidderLocation: 'Talatona',
        amount: 520000,
        timestamp: '2026-09-28T21:15:00Z',
      },
      {
        id: 'bid_3',
        listingId: 'listing_2',
        bidderId: 'user_4',
        bidderName: 'Tânia Baptista',
        bidderLocation: 'Lobito',
        amount: 580000,
        timestamp: '2026-09-29T05:20:00Z',
      },
    ],
    images: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80'
    ],
    sellerId: 'user_1',
    province: 'Luanda',
    city: 'Luanda',
    neighborhood: 'Maianga',
    createdAt: '2026-09-28T10:00:00Z',
    isSold: false,
    reactions: { like: 42, fire: 28, deal: 19, negotiate: 33 },
    userReactions: [{ userId: 'user_current', type: 'fire' }],
    viewsCount: 710,
  },
  {
    id: 'listing_3',
    title: 'PlayStation 5 Digital 825GB + 2 Comandos DualSense',
    description: 'Consola PS5 seminova, pouco usada por falta de tempo. Vai com 2 comandos originais sem drift, cabo HDMI de alta velocidade e base vertical. Encontro no Belas Shopping ou Kero de Talatona.',
    category: 'Informática & Eletrónica',
    condition: 'como_novo',
    type: 'fixed',
    price: 490000,
    images: [
      'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&auto=format&fit=crop&q=80'
    ],
    sellerId: 'user_3',
    province: 'Luanda',
    city: 'Talatona',
    neighborhood: 'Morro Bento',
    createdAt: '2026-09-29T02:00:00Z',
    isNegotiable: true,
    isSold: false,
    reactions: { like: 56, fire: 39, deal: 22, negotiate: 40 },
    userReactions: [],
    viewsCount: 890,
  },
  {
    id: 'listing_4',
    title: 'LEILÃO: Mesa de Sala de Jantar Rústica (Madeira Maciça) + 6 Cadeiras',
    description: 'Mesa de refeições rústica feita em madeira de mussivi de alta durabilidade. Motivo de venda: mudança de apartamento. Está perfeita e sólida. Quem der o melhor lance leva!',
    category: 'Eletrodomésticos & Casa',
    condition: 'como_novo',
    type: 'auction',
    price: 180000,
    currentBid: 240000,
    minIncrement: 10000,
    auctionEndsAt: inDays(2),
    bids: [
      {
        id: 'bid_4_1',
        listingId: 'listing_4',
        bidderId: 'user_1',
        bidderName: 'Manuel Kassoma',
        bidderLocation: 'Maianga',
        amount: 200000,
        timestamp: '2026-09-27T16:00:00Z',
      },
      {
        id: 'bid_4_2',
        listingId: 'listing_4',
        bidderId: 'user_3',
        bidderName: 'Kelson Domingos',
        bidderLocation: 'Talatona',
        amount: 240000,
        timestamp: '2026-09-28T19:30:00Z',
      },
    ],
    images: [
      'https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=800&auto=format&fit=crop&q=80'
    ],
    sellerId: 'user_2',
    province: 'Luanda',
    city: 'Belas',
    neighborhood: 'Kilamba',
    createdAt: '2026-09-27T12:00:00Z',
    isSold: false,
    reactions: { like: 19, fire: 8, deal: 14, negotiate: 9 },
    userReactions: [],
    viewsCount: 420,
  },
  {
    id: 'listing_5',
    title: 'Smart TV Samsung 50" Crystal UHD 4K (Série AU7000)',
    description: 'Televisor inteligente Samsung com suporte para Netflix, YouTube, DStv Now e Prime Video. Imagem e som espetaculares. Inclui comando inteligente e pés de apoio. Entrega na Restinga do Lobito ou envio acordado para Luanda.',
    category: 'Informática & Eletrónica',
    condition: 'bom_estado',
    type: 'fixed',
    price: 285000,
    images: [
      'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=800&auto=format&fit=crop&q=80'
    ],
    sellerId: 'user_4',
    province: 'Benguela',
    city: 'Lobito',
    neighborhood: 'Restinga',
    createdAt: '2026-09-28T09:15:00Z',
    isNegotiable: true,
    isSold: false,
    reactions: { like: 31, fire: 15, deal: 20, negotiate: 18 },
    userReactions: [],
    viewsCount: 520,
  },
  {
    id: 'listing_6',
    title: 'LEILÃO: Carrinho de Bebé Chicco Trio + Ovo Automóvel',
    description: 'Carrinho de bebé completo com alcofa e cadeira para carro. Muito leve, dobrável, cabe fácil na mala do carro. Tecido limpo e higienizado. Pouco uso.',
    category: 'Moda & Bebés',
    condition: 'bom_estado',
    type: 'auction',
    price: 85000,
    currentBid: 110000,
    minIncrement: 5000,
    auctionEndsAt: inHours(6),
    bids: [
      {
        id: 'bid_6_1',
        listingId: 'listing_6',
        bidderId: 'user_current',
        bidderName: 'Kieza Andrade',
        bidderLocation: 'Cazenga',
        amount: 95000,
        timestamp: '2026-09-28T20:00:00Z',
      },
      {
        id: 'bid_6_2',
        listingId: 'listing_6',
        bidderId: 'user_1',
        bidderName: 'Manuel Kassoma',
        bidderLocation: 'Maianga',
        amount: 110000,
        timestamp: '2026-09-29T04:10:00Z',
      },
    ],
    images: [
      'https://images.unsplash.com/photo-1591088398332-8a7791972843?w=800&auto=format&fit=crop&q=80'
    ],
    sellerId: 'user_2',
    province: 'Luanda',
    city: 'Belas',
    neighborhood: 'Kilamba',
    createdAt: '2026-09-28T11:00:00Z',
    isSold: false,
    reactions: { like: 15, fire: 4, deal: 12, negotiate: 8 },
    userReactions: [],
    viewsCount: 305,
  },
  {
    id: 'listing_7',
    title: 'Ténis Nike Air Jordan 1 Low Originais - Tam. 42',
    description: 'Calçado original comprado na África do Sul, usado apenas 3 vezes. Em caixa. Sola impecável, sem odores. Combinamos na Maianga.',
    category: 'Moda & Acessórios',
    condition: 'como_novo',
    type: 'fixed',
    price: 45000,
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80'
    ],
    sellerId: 'user_1',
    province: 'Luanda',
    city: 'Luanda',
    neighborhood: 'Maianga',
    createdAt: '2026-09-27T18:00:00Z',
    isNegotiable: false,
    isSold: true,
    reactions: { like: 28, fire: 19, deal: 7, negotiate: 12 },
    userReactions: [],
    viewsCount: 610,
  },
  {
    id: 'listing_8',
    title: 'Máquina de Lavar Roupa Samsung 9kg EcoBubble',
    description: 'Máquina de lavar automática em perfeito estado de funcionamento, silenciosa e com poupança de água e energia. Venda por motivo de mudança de casa. Retirada no Cazenga (Hoji-ya-Henda) ou entrego com frete acordado.',
    category: 'Eletrodomésticos & Casa',
    condition: 'bom_estado',
    type: 'fixed',
    price: 195000,
    images: [
      'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=800&auto=format&fit=crop&q=80'
    ],
    sellerId: 'user_current',
    province: 'Luanda',
    city: 'Cazenga',
    neighborhood: 'Hoji-ya-Henda',
    createdAt: '2026-09-29T04:00:00Z',
    isNegotiable: true,
    isSold: false,
    reactions: { like: 14, fire: 6, deal: 9, negotiate: 11 },
    userReactions: [],
    viewsCount: 230,
  },
  {
    id: 'listing_9',
    title: 'LEILÃO: Computador Portátil Lenovo ThinkPad T480 Core i7 / 16GB RAM / SSD 512GB',
    description: 'Portátil corporativo muito robusto, bateria dupla com autonomia de mais de 5 horas. Teclado retroiluminado, ecrã Full HD IPS. Excelente para programadores, estudantes e escritório em Viana.',
    category: 'Informática & Eletrónica',
    condition: 'como_novo',
    type: 'auction',
    price: 210000,
    currentBid: 250000,
    minIncrement: 10000,
    auctionEndsAt: inHours(20),
    bids: [
      {
        id: 'bid_9_1',
        listingId: 'listing_9',
        bidderId: 'user_1',
        bidderName: 'Manuel Kassoma',
        bidderLocation: 'Maianga',
        amount: 230000,
        timestamp: '2026-09-28T23:00:00Z',
      },
      {
        id: 'bid_9_2',
        listingId: 'listing_9',
        bidderId: 'user_3',
        bidderName: 'Kelson Domingos',
        bidderLocation: 'Talatona',
        amount: 250000,
        timestamp: '2026-09-29T05:30:00Z',
      }
    ],
    images: [
      'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&auto=format&fit=crop&q=80'
    ],
    sellerId: 'user_2',
    province: 'Luanda',
    city: 'Viana',
    neighborhood: 'Estalagem',
    createdAt: '2026-09-28T16:00:00Z',
    isSold: false,
    reactions: { like: 36, fire: 22, deal: 18, negotiate: 25 },
    userReactions: [],
    viewsCount: 480,
  }
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev_1',
    sellerId: 'user_1',
    reviewerId: 'user_3',
    reviewerName: 'Kelson Domingos',
    reviewerLocation: 'Talatona, Luanda',
    rating: 5,
    comment: 'Excelente negociação! Encontrámo-nos no largo da Maianga, o Manuel foi super pontual e o telemóvel estava exatamente como descrito nas fotos. Recomendo 100%.',
    date: '2026-09-25',
    transactionItemTitle: 'iPhone 11 64GB Preto',
    recommended: true,
  },
  {
    id: 'rev_2',
    sellerId: 'user_1',
    reviewerId: 'user_2',
    reviewerName: 'Esperança dos Santos',
    reviewerLocation: 'Kilamba, Luanda',
    rating: 5,
    comment: 'Pessoa muito séria e transparente. Deixou-me testar o artigo com calma antes de fazer a transferência por Multicaixa Express. Zungueiro de honra!',
    date: '2026-09-20',
    transactionItemTitle: 'Auriculares AirPods Pro 2',
    recommended: true,
  },
  {
    id: 'rev_3',
    sellerId: 'user_2',
    reviewerId: 'user_1',
    reviewerName: 'Manuel Kassoma',
    reviewerLocation: 'Maianga, Luanda',
    rating: 5,
    comment: 'Comprei uma mesa de centro com a dona Esperança no Kilamba. Artigo muito bem conservado, embalado com todo o cuidado.',
    date: '2026-09-18',
    transactionItemTitle: 'Mesa de Centro de Vidro',
    recommended: true,
  },
  {
    id: 'rev_4',
    sellerId: 'user_3',
    reviewerId: 'user_current',
    reviewerName: 'Kieza Andrade',
    reviewerLocation: 'Cazenga, Luanda',
    rating: 5,
    comment: 'Negociámos um comando de PS5 no Belas Shopping. Muito confiável e atencioso.',
    date: '2026-09-22',
    transactionItemTitle: 'Comando DualSense Midnight Black',
    recommended: true,
  }
];

export const INITIAL_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv_1',
    listingId: 'listing_1',
    buyerId: 'user_current',
    sellerId: 'user_1',
    lastMessageText: 'Combinado! Podemos encontrar-nos amanhã às 15h em frente à Shoprite da Maianga?',
    lastMessageTimestamp: '2026-09-29T06:10:00Z',
    unreadCount: 1,
  },
  {
    id: 'conv_2',
    listingId: 'listing_3',
    buyerId: 'user_current',
    sellerId: 'user_3',
    lastMessageText: 'Qual é o preço mínimo que faz para fechar hoje no Belas Shopping?',
    lastMessageTimestamp: '2026-09-28T22:30:00Z',
    unreadCount: 0,
  }
];

export const INITIAL_MESSAGES: Message[] = [
  {
    id: 'msg_1',
    conversationId: 'conv_1',
    senderId: 'user_current',
    text: 'Olá Manuel, tudo bem? Vi o iPhone 12 Pro que publicou na Zunga. A bateria ainda aguenta o dia todo?',
    timestamp: '2026-09-29T05:40:00Z',
    read: true,
  },
  {
    id: 'msg_2',
    conversationId: 'conv_1',
    senderId: 'user_1',
    text: 'Olá Kieza! Sim, está com 87% de saúde de bateria, com uso normal aguenta bem o dia inteiro. Posso mostrar o relatório das definições.',
    timestamp: '2026-09-29T05:52:00Z',
    read: true,
  },
  {
    id: 'msg_3',
    conversationId: 'conv_1',
    senderId: 'user_current',
    text: 'Ótimo. Faz por 300.000 Kz em dinheiro ou transferência imediata?',
    isOffer: true,
    offerAmount: 300000,
    timestamp: '2026-09-29T06:01:00Z',
    read: true,
  },
  {
    id: 'msg_4',
    conversationId: 'conv_1',
    senderId: 'user_1',
    text: 'Combinado! Fechamos nos 300.000 Kz. Podemos encontrar-nos amanhã às 15h em frente à Shoprite da Maianga? Tem seguranças e muito movimento, é seguro para ambos.',
    proposedLocation: 'Shoprite da Maianga (Ponto Público Seguro)',
    timestamp: '2026-09-29T06:10:00Z',
    read: false,
  },
  {
    id: 'msg_5',
    conversationId: 'conv_2',
    senderId: 'user_current',
    text: 'Qual é o preço mínimo que faz para fechar hoje no Belas Shopping?',
    timestamp: '2026-09-28T22:30:00Z',
    read: true,
  }
];

export const ANGOLAN_PROVINCES = [
  'Luanda',
  'Benguela',
  'Huambo',
  'Huíla',
  'Cabinda',
  'Cuanza Sul',
  'Cuanza Norte',
  'Uíge',
  'Malanje',
  'Zaire',
  'Namibe',
  'Bié',
  'Moxico',
  'Cunene',
  'Lunda Norte',
  'Lunda Sul',
  'Cuando Cubango',
  'Bengo',
];

export const ANGOLA_MUNICIPALITIES_AND_NEIGHBORHOODS: Record<string, Record<string, string[]>> = {
  Luanda: {
    'Luanda': ['Maianga', 'Alvalade', 'Ingombota', 'Mutamba', 'Maculusso', 'Rangel', 'Sambizanga', 'Palanca', 'Vila Alice'],
    'Talatona': ['Morro Bento', 'Benfica', 'Camama', 'Futungo', 'Lar do Patriota'],
    'Belas': ['Kilamba', 'Cabolombo', 'Barra do Kwanza', 'Ramiros'],
    'Cazenga': ['Hoji-ya-Henda', 'Mabor', 'Tala Hady', 'Kalawenda', 'Cazenga Popular'],
    'Viana': ['Estalagem', 'Zango 1 a 5', 'Viana Sede', 'Calumbo', 'Kikuxi'],
    'Cacuaco': ['Cacuaco Sede', 'Kicolo', 'Funda', 'Sequele'],
    'Icolo e Bengo': ['Catete', 'Bela Vista', 'Cassoneca'],
    'Quiçama': ['Muxima', 'Demba Chio', 'Quixinge'],
  },
  Benguela: {
    'Lobito': ['Restinga', 'Caponte', 'Bela Vista', 'Canata', 'Alto Liro', 'Compão'],
    'Benguela': ['Centro', 'Benfica', 'Zona A', 'Navegantes', 'Cassoco'],
    'Catumbela': ['Catumbela Centro', 'Luongo', 'São Pedro'],
    'Baía Farta': ['Baía Farta Sede', 'Calohombo'],
  },
  Huambo: {
    'Huambo': ['Cidade Alta', 'São Pedro', 'Fátima', 'Lossambo', 'Santo António'],
    'Caála': ['Caála Sede', 'Catata', 'Cuima'],
    'Bailundo': ['Bailundo Sede', 'Lunge', 'Hengue'],
  },
  Huíla: {
    'Lubango': ['Centro', 'Mapunda', 'Lage', 'Arco-Íris', 'Comercial', 'Senhora do Monte'],
    'Humpata': ['Humpata Centro', 'Neves'],
    'Chibia': ['Chibia Sede', 'Capunda Cavilongo'],
  },
  Cabinda: {
    'Cabinda': ['Cabinda Centro', 'Simindele', 'Luvassa', 'Chibodo'],
    'Cacongo': ['Landana', 'Massabi'],
  },
  'Cuanza Sul': {
    'Sumbe': ['Sumbe Centro', 'Gungo', 'Quicombo'],
    'Porto Amboim': ['Porto Amboim Sede', 'Capolo'],
  },
};

export const POPULAR_NEIGHBORHOODS: Record<string, string[]> = {
  Luanda: [
    'Maianga',
    'Talatona',
    'Kilamba',
    'Cazenga',
    'Viana',
    'Alvalade',
    'Ingombota',
    'Mutamba',
    'Maculusso',
    'Morro Bento',
    'Benfica',
    'Camama',
    'Sambizanga',
    'Rangel',
    'Cacuaco',
    'Palanca',
    'Mabor'
  ],
  Benguela: ['Lobito - Restinga', 'Benguela - Centro', 'Baía Farta', 'Catumbela', 'Compão'],
  Huambo: ['Cidade Alta', 'São Pedro', 'Fátima', 'Lossambo'],
  Huíla: ['Lubango - Centro', 'Mapunda', 'Lage', 'Arco-Íris'],
};

export const CATEGORIES = [
  'Todos',
  'Telemóveis & Tablets',
  'Informática & Eletrónica',
  'Ferramentas & Geradores',
  'Eletrodomésticos & Casa',
  'Moda & Acessórios',
  'Moda & Bebés',
  'Veículos & Peças',
  'Desporto & Lazer'
];

export const SAFE_MEETING_POINTS = [
  'Shoprite (Maianga / Palanca / Viana)',
  'Kero (Talatona / Kilamba / Morro Bento)',
  'Belas Shopping (Talatona)',
  'Luanda Shopping / Maculusso',
  'Largo 1º de Maio (Centro da Cidade)',
  'Bombas Sonangol (com loja de conveniência)',
  'Candando (Morro Bento / Kilamba)'
];
